version: "3.9"  # optional since v1.27.0
services:
  web:
    stdin_open: true
    tty: true
    build: .
    command: yarn dev
    ports:
      - "3000"
    volumes:
      - .:/src/app
      - logvolume01:/var/log
    depends_on:
      - database
  database:
    image: 'postgres:9.6-alpine'
    command:  '-c shared_buffers=256MB -c max_connections=200'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
volumes:
  logvolume01: {}
  database: {}